
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: school
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schools
    username: root
    password: root
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  config:
    student-service: http://localhost:8091/students

server:
  port: 8070


